development:
  inventory_capacity: 20
  experience_per_level: 1000
  experience_percent_lost: 10
  potion_heal_percent: 10
  item_prefixes: 'colossus, entropy, powered, bone, echoing, stone, gyre, dread, imp, viper, shivering, toxic'
  item_suffixes: 'ghoul, hope, luck, fortune, greed, strength, daring, envy, ire, freedom, carnage, destruction'
  item_types: 'amulet, ring, sword, blade, dagger, flail, club, axe, bow, crossbow'

production:
  inventory_capacity: 20
  experience_per_level: 1000
  experience_percent_lost: 10
  potion_heal_percent: 10
  item_prefixes: 'colossus, entropy, powered, bone, echoing, stone, gyre, dread, imp, viper, shivering, toxic'
  item_suffixes: 'ghoul, hope, luck, fortune, greed, strength, daring, envy, ire, freedom, carnage, destruction'
  item_types: 'amulet, ring, sword, blade, dagger, flail, club, axe, bow, crossbow'

test:
  inventory_capacity: 5
  experience_per_level: 1000
  experience_percent_lost: 10
  potion_heal_percent: 10
  item_prefixes: 'colossus, entropy, powered, bone, echoing, stone, gyre, dread, imp, viper, shivering, toxic'
  item_suffixes: 'ghoul, hope, luck, fortune, greed, strength, daring, envy, ire, freedom, carnage, destruction'
  item_types: 'amulet, ring, sword, blade, dagger, flail, club, axe, bow, crossbow'
