FactoryGirl.define do
  sequence(:name, 1) { |n| "Autogenerated_item_#{n}" }
  sequence(:username, 1) { |n| "User_#{n}" }

  factory :item do
    name
  end

  factory :inventory do
  end

  factory :player do
  end

  factory :player_class do
  end

  factory :account do
    username
  end
end
